### ISSUE TITLE
IHC Visual Controller

### ISSUE THREAD

**Issue by taisholland** [dingusdk/PythonIhcSdk#1]
Really cool project!

i am today using openhab to integrate with my ihc controller and it is working ok
i am now trying to migrate my openhab installtion to Home Assistant and found your lib.

my controller will only serve APIs over https and when i try to run "python3 ihctest.py https://ip username password" i get a starange ssl error.
 Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 816, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: PARSE_TLSEXT] parse tlsext (_ssl.c:720)

i am using python 3.5.3 on Ubuntu 17

do you have any idea why it is not working

it might be worth mentioning that IHC Captain also works ok with my IHC controller

**Comment by dingusdk** [comment]
There are 1 or maybe 2 problems using https. The first problems is that the controller do not have a certificate that will match the url you use to make requests. This can be usually be fixed by ignoring the wrong certificate, or better accept the specific certificate in the controller.
The second problem can be that the controller is using an ssl protocol that is considered not safe in newer implementations of ssl. I think this is what is happening in your case since there is something about "do_handshake" in the error
I am new to python so not sure exactly how this is done in python, but I will look into it.

Are you not able to enable http in the administrator application for the controller? Or is it because you have the controller on a different location.

**Comment by taisholland** [comment]
I think you are right regarding ssl certificate and ssl protocol.
I cant enable http… it is a the controller without viewer

**Comment by dingusdk** [comment]
I have now spend a lot of time trying to get this to work, and I am 99% sure it is a protocol/cipher issue. I did find a way to force TLSv1 and AES256-SHA - here is a simple test I did:

    class TLSv1Adapter(HTTPAdapter):
        CIPHERS = ('AES256-SHA')
        def init_poolmanager(self, *args, **kwargs):
            context = create_urllib3_context(ciphers=self.CIPHERS,ssl_version=ssl.PROTOCOL_TLSv1)
            context.verify_mode = 0
            kwargs['ssl_context'] = context
            return super(TLSv1Adapter, self).init_poolmanager(*args, **kwargs)

        def proxy_manager_for(self, *args, **kwargs):
            context = create_urllib3_context(ciphers=self.CIPHERS,ssl_version=ssl.PROTOCOL_TLSv1)
            context.verify_mode = 0
            kwargs['ssl_context'] = context
            return super(TLSv1Adapter, self).proxy_manager_for(*args, **kwargs)

    s = requests.Session()
    s.mount('https://192.168.1.3', TLSv1Adapter())
    r = s.get('https://192.168.1.3/wsdl/authentication.wsdl', verify=False)

But the above still fails, and I think it is an issue in the "requests" or "urllib3" module. 
If I try using curl on a command line I get a handshake failed error too, but it works if I force tlsv1/ciphers and ignore host verification like this:

    curl --tlsv1.0 --ciphers AES256-SHA  --insecure https://my-ihc-ip/wsdl/authentication.wsdl

I can also get it to work using the PyCurl module, but PyCurl is not available on the newest python 3.6 and is more difficult to get working on windows. When using PyCurl I have to set these options:

    c.setopt(c.SSL_CIPHER_LIST,"AES256-SHA")
    c.setopt(c.SSLVERSION,c.SSLVERSION_TLSv1_0)
    c.setopt(c.SSL_VERIFYHOST,0)
    c.setopt(c.SSL_VERIFYPEER,0)

I cannot find the SSL_VERIFYPEER option in the requests/urllib3

**If anybody know how to get this working in requests/urllib3 please let me know**

**Comment by dingusdk** [comment]
I the new release 2.0.0 I have separated the connection from the soap client, and made an alternative pycurl implementation. This can be used to do a ssl connection to the controller.
(Pycurl is slower that the standard connection, and is not available for the newest python on windows)
To use it replace the connecting after you have create the IHCController object - see the example.
I have also made a class to do the ssl using the standard "resuests" module and forcing Tslv1 and AES256-SHA, but it does not work. I will leave the code here in case somebody else can get it working. (If you do please let me know)
