### ISSUE TITLE
get_user_log() has an error

### ISSUE THREAD

**Issue by gregersn** [dingusdk/PythonIhcSdk#2]
`In [9]: ihc.client.get_user_log()
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-9-ea4b8b2c32af> in <module>()
----> 1 ihc.client.get_user_log()

~/devel/priv/PythonIhcSdk/ihcsdk/ihcclient.py in get_user_log(self, language)
    243             if not base64data:
    244                 return False
--> 245             compresseddata = base64.b64decode(base64data)
    246             return zlib.decompress(compresseddata, 16+zlib.MAX_WBITS).decode('ISO-8859-1')
    247         return False

error: Error -3 while decompressing data: incorrect header check`

If, I however, just do 
`            compresseddata = base64.b64decode(base64data)
            return (compresseddata.decode('UTF-8'))
`
in ihcclient.py/get_user_log

I get a correctly formatted log in my console. So it might be that my version of the IHC doesn't compress the log on output?

**Comment by dingusdk** [comment]
Thank you for the feedback.
This was my mistake. My log on the controller did not contain any data when I verified this. I was assuming the data was encoded the same way as the project, but I remembered wrong, since that is not the case.
It should be working in the new release 2.1.1
